### ISSUE TITLE
Install instructions show `liquid-tether`?

### ISSUE THREAD

**Issue by jacobq** [pzuraq/liquid-wormhole#15]
Isn't `liquid-wormhole` different from `liquid-tether`? Could you please add some information explaining what the differences are or which one we should use? (e.g. is one a successor to the other?)

**Comment by pzuraq** [comment]
`liquid-wormhole` is different from `liquid-tether`, that was my mistake in the ReadMe, will fix it.

`liquid-wormhole` is the underlying animation logic for `liquid-tether`. Basically, `liquid-tether` without Tether.js. It's for when you want to provide your own positioning logic, or use a different library than Tether.js.

**Comment by jacobq** [comment]
Thanks for the fast reply and brief explanation. I just want to be able to animate components like modals in my ember-electron app, so it sounds like I should use `liquid-tether`. Would you like me to attempt a PR on the `README.md` to explain this? I think it would be helpful to others like me who are trying to figure this stuff out....there is just so much to learn.

**Comment by pzuraq** [comment]
Yeah, definitely! I have the unfortunate problem that I have a hard time making the docs easy to follow for beginners, cause I built the thing 😬  Feel free to submit a PR, help is always welcome. 

I recommend using `liquid-tether` in general, but sometimes it doesn't work well for certain use cases. If you need any help figuring it out feel free to ping me on the Ember community Slack, or pop into #topic-animation
