### ISSUE TITLE
100vw causes horizontal scrollbar

### ISSUE THREAD

**Issue by davewasmer** [pzuraq/liquid-wormhole#22]
The use of `width: 100vw;` on [this line](https://github.com/pzuraq/liquid-wormhole/blob/master/addon/styles/addon.css#L25) causes the selected div to overflow the `<body>` width by the width of the browser's scrollbar if the body content is already overflowing vertically.

To see this in action, just disable the `overflow-x: hidden` rule on the `<body>` element of the docs site, and then shrink the browser window height until the vertical scroll bar appears:

![image](https://cloud.githubusercontent.com/assets/707213/22278772/3e9aaab0-e283-11e6-9034-b9c6ec377899.png)

`100vw` is 100% of the viewport width **not** accounting for scrollbars (unless [the root element has anything other than `overflow: auto` set](https://www.w3.org/TR/css3-values/#viewport-relative-lengths), but `auto` is the default value). Thus, when the page content overflows the viewport vertically, the browser renders the vertical scroll bar, which reduces the visible viewport area by a few pixels. But the `100vw` value doesn't update to account for this, so the selected div retains the same width as before the vertical scrollbar appeared. This results in the horizontal scroll bar rendering.

There's a few options (happy to PR any of them):

1. Require consumers of liquid-wormhole use `overflow-x: hidden` on the body element, and ship that with the default CSS that already ships. This is less than ideal, since it prevents any horizontal scrolling UIs (less common) and masks CSS bugs that might be causing unwanted horizontal overflow (more common).

2. Replace `100vw` with forced `width:100%` (same for height too probably) on each ancestor element, all the way down to that selected div.

3. Replace `100vw` with forced `left: 0; right: 0` (and so on for top/bottom) on each ancestor element, all the way down to that select div.

I'm not sure of the tradeoffs between (2) and (3) off the top of my head. In this case, they seem identical, but it's CSS, so :man_shrugging:

For any others hitting this, a temporary workaround is to apply (2) or (3) via your own CSS, overriding the default CSS that ships with the addon.

**Comment by pzuraq** [comment]
Let's go ahead and try replacing it with `width: 100%`, that should probably be fine and may work without styling all the ancestors that way (they should all be 100% of the viewport already). Got a little to trigger happy with the viewport units 😛

Thanks for pointing it out and coming up with solutions! Let me know if you need any help figuring it out, that CSS is a little touchy. I actually discovered it by accident, that you could have a `visibility: visible` child of a `visibility: hidden` parent. I think it should all work out fine though, but as you said, CSS :man_shrugging:

**Comment by davewasmer** [comment]
Well, my suggestion didn't work exactly ;)

The `width:100%` is needed on all the ancestors because once tether.js switches to absolute positioning, the child elements will collapse to zero width/height (because 100% of 0 is still 0). So you need `width:100%` on each containing element up the DOM to ensure that when the child element says `100%`, it has some width to measure against.

Unfortunately, this causes other problems - those containing divs that are forced to `width:100%` then "mask" the rest of the UI, capturing click and hover events.

This can be resolved using the trick you mentioned (which I learned from this codebase myself!) of making the containing divs `visibility:hidden`. Thus they won't capture any interactions, but the child element itself will be `visibility:visible`.

But I'm not sure if this will have other side effects - I don't fully grok the role of each of the containing divs, so not sure if setting `visibility:hidden` on them would do other nasty things. @pzuraq do you know of any adverse side effects to this approach?

Here's a quick screen grab of what I'm proposing:

![image](https://cloud.githubusercontent.com/assets/707213/22299758/8d1d537c-e2e2-11e6-9fd4-4738cdbc3911.png)

**Comment by pzuraq** [comment]
I don't think that there would be any negative side effects by making all of the intermediate divs `visibility: hidden`, since we're relying on that special behavior anyways. 

This entire hack is to get around the fact that liquid-fire animations base their animations directly on the parent of the animated item, and for us that is supposed to be the "window" or viewport. So having a hidden, non-interactable parent was the goal. I'm still looking for better ways to get this behavior, so if you have any ideas feel free to explore them, for now we should be able to rely on the hidden-parent/visible-child behavior.
