### ISSUE TITLE
Compatiblity with Glimmer 2

### ISSUE THREAD

**Issue by jfarlow** [pzuraq/liquid-wormhole#23]
Is there any way to update liquid-wormhole to be compatible with Glimmer 2?

Specifically I think this issue is affecting how liquid-wormhole works:
https://github.com/yapplabs/ember-wormhole#what-version-of-ember-is-this-compatible-with

I don't know enough structure to really know what I'm doing, but if in `liquid-womrhole.hbs` I wrap the {{#if hasSend}}{{/if}} argument in a div the the worm hole completely breaks.

`<div>
{{#if hasSend}}{{/if}}
</div`

Any thoughts or suggestions?

**Comment by jfarlow** [comment]
I notice if I replace the entire block in `liquid-wormhole.hbs` with:

`<div id={{wormholeId}} class="{{wormholeClass}} liquid-wormhole-element">
     {{yield}}
  </div>`

Then wormhole works again.  (though the default ember CSS is overriding the liquid-wormhole css and requires me to make !important the position and top values:

`.default-liquid-destination {
  position: absolute !important;
  top: 0  !important;
  z-index: 9999;
}`

Then we're back in business.  But I bet I broke some capability by removing the entire `{{#if hasSend}}` and `{{#if hasBlock}}` conditional trees.

**Comment by pzuraq** [comment]
The only functionality there was being able to directly send a `component`, which I haven't seen used too much personally, but we definitely can't remove it without breaking changes. However, we can probably add a stable root level `div` to the whole thing to give it that stability. Wanna submit a PR to get that added?

**Comment by jfarlow** [comment]
Simply adding a `div` at root doesn't seem to work.  I suspect there are some calls to `entity.parent()` and `entity.children()` that are presuming there is *not* a top level `div`.  I'm not familiar enough with the code to know if that's actually the case or how to fix it.

**Comment by pzuraq** [comment]
Ok, will take a look and try to get this sorted, Glimmer 2 compat is definitely a goal for this addon

**Comment by pzuraq** [comment]
@jfarlow I'm taking a look at this now, can't seem to find any issues with just using the latest Ember. What versions of Ember/Liquid Fire are you using? And what does your config look like?

**Comment by jfarlow** [comment]
I'm currently using:

- Ember: 2.11.0
- liquidFire: 0.27.0
- liquidTether: 2.0.3
- ember-wormhole: 0.5.1

still same issue - without removing the conditional at root, there is no displayed content.  I'm setting the content programmatically, so the content itself is called as a component.

`{{liquid-tether-object ...}}
        {{content-object content=content}}
 {{/liquid-tether-object}}
`

**Comment by pzuraq** [comment]
Interesting. So is `liquid-tether-object` a new component that you made? And what is `content-object` doing? I have a test where there is a component that is rendered directly in a `liquid-wormhole` and it seems to be working so I'm guessing there's something unique about your setup

**Comment by jfarlow** [comment]
Here's the tether object:

```
{{#if session.isAuthenticated}}
	{{#liquid-tether classPrefix='guide' target=guide.currentTargetElementID attachment=guide.attachment targetAttachment=guide.targetAttachment offset=guide.offset}}
		<div>
			{{guide-box content=guide.content header=guide.header subheader=guide.subheader content=guide.content}}
		</div>
	{{/liquid-tether}}
{{/if}}
```


and here's the target added elsewhere on the page:
```
{{guide-tab guideIndex=1 header='Welcome' subheader=null content='A popover guide' attachment='top center' targetAttachment='bottom middle' offset='0 10'}}	
```

I have a 'guide' service that coordinates to link the attachment.  And this does not actually seem to be the problem.  The links are all established in time and appear correctly.  If I change or unhook the links then I do get reasonable errors.  And the same code with direct linkage between the 'guide box' and the 'guide-tab' still has the same issues.

I have tried the liquid tether with/without the enclosing div enclosing the guide.

Currently, in order to get it to work I have edited the liquid-wormhole/addon/templates/components/liquid-wormhole.hbs to *just* be:

```
	  <div id={{wormholeId}} class="{{wormholeClass}} liquid-wormhole-element">
					{{yield}}
		  </div>
<--- OLD CODE --->
```

**Comment by pzuraq** [comment]
Yeah, I have the same setup with a component at the root of the `liquid-tether`, still can't get it to not show up.

Can you reproduce this issue in an Ember Twiddle, or in the dummy app? Or ping me on Slack so we can narrow it down and figure out exactly what's causing this?

**Comment by pzuraq** [comment]
I'm not able to reproduce this as is, so I'm going to close for now. If you can submit a failing test or a twiddle that reproduces the failure I'll gladly dive in and figure out what's going on.
