### ISSUE TITLE
animating on route transition?

### ISSUE THREAD

**Issue by evoactivity** [pzuraq/liquid-wormhole#42]
If I have a liquid-wormhole in a route template and I transition to that route how can I animate the wormholed content?

In my use case I have a button that needs to float on top of everything else, I'm using liquid-fire for page transitions and I want the button to be animated as well but this doesn't seem possible?

**Comment by pzuraq** [comment]
So you want to have the button animate in when the user enters the route?

**Comment by pzuraq** [comment]
I believe it should be possible to animate in wormholes when you enter a route, it should be similar to the way liquid-tether uses this library (see the [documentation app there for examples](http://pzuraq.github.io/liquid-tether/#/))

**Comment by pzuraq** [comment]
Closing this issue, feel free to reopen if it's still a problem
