### ISSUE TITLE
Ember.WeakMap is not a constructor

### ISSUE THREAD

**Issue by SanthoshRaju91** [pzuraq/liquid-wormhole#52]
Hi, 

We have been using liquid-wormhole addon, and from your recent version release we are getting an issue. 

`Ember.WeakMap is not a constructor.`

Currently our Ember app is on version 2.8.

Do we need to upgrade our ember app to higher version to resolve this issue ? Thanks

**Comment by pzuraq** [comment]
hmm, you shouldn't need to upgrade, `Ember.WeakMap` was included in Ember 2.8 and we also include the polyfill which should add it if it does not exist. Can you add steps to reproduce so I can dive in and take a look?

**Comment by SanthoshRaju91** [comment]
Steps, to reproduce.

1. Create new Ember application.
2. Install liquid tether addon (which has internal dependency for liquid-wormhole).
3. Write a animation code with liquid tether.
4. Serve the app.

From serving you will see that the app does not load and gives the above error message. As a work around, we have manually installed ember-weakmap ember addon, since it was blocking all our devs due to the issue.

**Comment by SanthoshRaju91** [comment]
Actually we are using liquid-tether addon, this addon has internal dependency to liquid wormhole. We did not get an issue for previous versions. But when we installed the dependencies we are getting the issue now.

As a work around we have installed the ember-weakmap addon in our maps. Since it is blocking our devs due to this issue.

**Comment by pzuraq** [comment]
Yeah, what's weird is that the bugfix in liquid-tether should have actually fixed the behavior of sub-addons like ember-weakmap. If you could make a simple application with liquid-tether that has this issue and push it to github, I can take a look and see what's going on directly

**Comment by SanthoshRaju91** [comment]
Thats the confusing part for me. When posting the issue I created a new application and included the liquid-tether, it didn't give me any issue.

Extremely sorry for confusing you, but this is happening when we are downloading the latest version in an existing app.

**Comment by pzuraq** [comment]
Interesting, to me that points to an issue with your version of ember-cli, or something unique to your setup that is causing this. If you can narrow it down, definitely open to help!

**Comment by knownasilya** [comment]
Also seeing this issue, just wiped my node_modules and reinstalled and the issue started happening.

```
TypeError: Ember.WeakMap is not a constructor
    at Module.callback (liquid-fire-transitions.js:9)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at requireModule (loader.js:27)
    at Class._extractDefaultExport (index.js:397)
    at Class.resolveOther (index.js:100)
    at Class.superWrapper [as resolveOther] (ember.debug.js:45374)
    at Class.resolve (ember.debug.js:12695)
```

Using Ember 2.14.1

```
npm ls liquid-wormhole
└─┬ liquid-tether@2.0.2
  └── liquid-wormhole@2.1.1
```

**Comment by knownasilya** [comment]
Upgrading to 2.0.6 seems to have solved the issue.

**Comment by SanthoshRaju91** [comment]
@knownasilya, after upgrading to 2.0.6 solved the issue for me. Thank you very much, but for older version we should install ember-weakmap manually.
