### ISSUE TITLE
Visibility issue with liquid-fire 0.29.3

### ISSUE THREAD

**Issue by ef4** [pzuraq/liquid-wormhole#58]
Hi @pzuraq, we [patched a visibility bug](https://github.com/ember-animation/liquid-fire/pull/607) in liquid-fire 0.29.3, but it appears that the bugfix [causes a visual regression when using liquid-wormhole](https://github.com/ember-animation/liquid-fire/issues/610).

Does the [proposed change to liquid-wormhole in that discussion](https://github.com/ember-animation/liquid-fire/issues/610#issuecomment-396106430) seem good to you?

**Comment by pzuraq** [comment]
Absolutely! Will comment there, PR would be welcome

**Comment by pzuraq** [comment]
This should have been resolved by #59
