### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by knownasilya** [pzuraq/liquid-wormhole#7]

**Comment by pzuraq** [comment]
Guessing this is for Ember Fastboot. Unfortunately I don't really see a way around this, the usage of `document` is in the transitions or in Tether.js itself, and DOM manipulation in general is key to how liquid wormhole works.

What I'd like to do is prevent liquid wormhole from doing it's thing until just after the application is loaded on the client. It's not ideal, but I don't see another way of it working.

**Comment by knownasilya** [comment]
Nope, I mean't to document how the liquid-wormhole should be used 👍 Sorry for the ambiguity.

**Comment by pzuraq** [comment]
ahhh, yeah that one is important haha! Will get on it 👍
